# .pages.yml — Pages CMS config for: team, work, services, posts, infopages
# Images live in src/images/{root files, blog, work, ...}

media:
  name: images
  label: Images
  input: src/images
  output: src/images
  path: ""   # start browsing at /src/images
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # ---------------------
  # TEAM
  # ---------------------
  - name: team
    label: Team
    type: collection
    path: src/content/team
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, role]
    fields:
      - { name: name,   label: Name, type: string, required: true }
      - { name: role,   label: Role, type: string }
      - { name: intro,  label: Intro, type: text }
      - name: education
        label: Education
        type: string
        list: true
      - name: experience
        label: Experience
        type: string
        list: true
      - name: avatar
        label: Avatar
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options: { media: images, path: . }   # use files like avatar1.jpeg
          - { name: alt, label: Alt text, type: string }

  # ---------------------
  # WORK
  # ---------------------
  - name: work
    label: Work
    type: collection
    path: src/content/work
    filename: "{primary}.md"
    view:
      primary: work
      fields: [work, company, year]
    fields:
      - { name: link,    label: Link, type: string }
      - { name: company, label: Company, type: string }
      - { name: year,    label: Year, type: string }
      - { name: client,  label: Client, type: string }
      - { name: work,    label: Work Title, type: string, required: true }
      - name: credits
        label: Credits
        type: object
        list: true
        fields:
          - { name: name, label: Name, type: string }
          - { name: role, label: Role, type: string }
      - name: thumbnail
        label: Thumbnail
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options: { media: images, path: work }   # src/images/work
          - { name: alt, label: Alt text, type: string }

  # ---------------------
  # SERVICES
  # ---------------------
  - name: services
    label: Services
    type: collection
    path: src/content/services
    filename: "{primary}.md"
    view:
      primary: service
      fields: [service]
    fields:
      - { name: service,     label: Service, type: string, required: true }
      - { name: description, label: Description, type: text }

  # ---------------------
  # POSTS
  # ---------------------
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, pubDate, author]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - { name: title,       label: Title, type: string, required: true }
      - { name: pubDate,     label: Publication Date, type: date }
      - { name: description, label: Description, type: text }
      - { name: author,      label: Author, type: string }
      - name: image
        label: Cover Image
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options: { media: images, path: blog }   # src/images/blog
          - { name: alt, label: Alt text, type: string }
      - { name: tags, label: Tags, type: string, list: true }

  # ---------------------
  # INFO PAGES
  # ---------------------
  - name: infopages
    label: Info Pages
    type: collection
    path: src/content/infopages
    filename: "{primary}.md"
    view:
      primary: page
      fields: [page, pubDate]
    fields:
      - { name: page,    label: Page, type: string, required: true }
      - { name: pubDate, label: Publication Date, type: date }
      - { name: body,    label: Body, type: rich-text }
